spring:
  datasource:
    #url: jdbc:h2:mem:todolist
    url: jdbc:h2:file:~/todolist
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: 3600

  messages:
    encoding: UTF-8
  # http:
  #   encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
    mode: HTML5

  #server:
  #  tomcat:
  #    uri-encoding: UTF-8

  #port: 5555
db:
  reset: false # erste "true" danach "false" auswahlen.// Users wird fest erstellt


ui:
  language: de # de oder en